# Generated by Django 4.0.2 on 2022-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('ifLogged', models.BooleanField(default=False)),
            ],
        ),
    ]
