# Generated by Django 4.0.2 on 2022-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_product_user_user_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
